# conda env create -f environment.yml
name: numlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - xarray
  - pooch # for xarray tutorial functions
  - proplot
  - cartopy
  - netcdf4
  - ipympl # for interactive widget matplotlib
