# conda env create -f environment.yml
name: numlab
channels:
  - conda-forge
  - defaults
dependencies:
  - xesmf
  - dask
  - xarray
  - pooch # for xarray tutorial functions
  - pandas 
  - scipy 
  - jupyter 
  - jupyterlab 
  - netcdf4 
  - proplot 
  - cartopy 
  - "matplotlib<=3.5" 
  - intake-esm # get CMIP6 data
  - python-graphviz 
  - nbresuse 
  - nc-time-axis 
  - nb_conda_kernels 
  - ipympl 
  - gcsfs 
  - zarr
  - cdsapi # usefull to access copernicus data store directly
