# conda env create -f environment.yml
name: numlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - xarray
  - pooch # for xarray tutorial functions
  - nc-time-axis # to deal with some time axis
  - proplot
  - matplotlib[version='<=3.5']
  - cartopy
  - xesmf
  - nbresuse # to see RAM
  - python-graphviz # for dask visualization
  - dask # for parallelization
  - nb_conda_kernels # allow changing kernel in a notebook
  - netcdf4
  - ipympl # for interactive widget matplotlib
