# conda env create -f environment.yml
name: numlab
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - pooch # for xarray tutorial functions
  - nc-time-axis # to deal with some time axis
  - proplot
  - matplotlib<=3.5
  - cartopy
  - intake-esm # get CMIP6 data
  - xesmf # regrid
  - isort
  - esmpy
  - black
  - nbresuse # to see RAM
  - nodejs[version='>=10.0'] # for jupyterlab
  - python-graphviz # for dask visualization
  - dask # for parallelization
  - nb_conda_kernels # allow changing kernel in a notebook
  - netcdf4
  - jupyterlab_code_formatter
  - jupyterlab
  - jupyter
  - gcsfs # Google Cloud (for intake-esm)
  - zarr # similar to netCDF but more performant (for intake also)
  - cdsapi # usefull to access copernicus data store directly
  - ipympl # for interactive widget matplotlib

